### ISSUE TITLE
Client ID and Pass Authentication

### ISSUE THREAD

**Issue by CreationP** [iit-Demokritos/PServer#5]
The server does not authenticate the Client Name and therefore attributes can be passed without the Client being registered to the SQL. The same goes for the Clients' Password.

**Comment by nickzorb** [comment]
Isn't this the same as issue #4?

**Comment by CreationP** [comment]
No, because #4 is about password authentication. What we found out is that Client name is getting no authentication also therefore parameters can be passed from incorrect clients (client that do not exist).

**Comment by nickzorb** [comment]
Oh, I see, well the commits that fixed #4 and #3 also fix this one unless I am mistaken. If they don't please let me know. There hasn't been a merge yet so you can get the latest version from my repo.
